/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fja.view;
import br.edu.fja.model.DaoUtil;
import java.sql.*;
//import br.edu.fja.dao.ModuloConexao2;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author evawellesrodrigues
 */
public class TelaPrincipalView extends javax.swing.JFrame {
   
    //ModuloConexao2  conecta =   new ModuloConexao2();
  
    
    Connection conexao = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public TelaPrincipalView() throws SQLException {
        initComponents();
        conexao = DaoUtil.conector();
       // conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        painelInterno = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCadastroEstacionamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCadastroMotoristas = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnGps = new javax.swing.JButton();
        btnRegistroVagas = new javax.swing.JButton();
        btnPagamento = new javax.swing.JButton();
        bntFecharTelaBemVindo = new javax.swing.JButton();
        labelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        menuUsuarioAdminView = new javax.swing.JMenuItem();
        menuCadastroVagas = new javax.swing.JMenu();
        menuCadastroEstacionamento = new javax.swing.JMenuItem();
        menuCadastroVaga = new javax.swing.JMenuItem();
        menuCadastroMotorista = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        menuGuardarRegistroVaga = new javax.swing.JMenuItem();
        menuGps = new javax.swing.JMenu();
        menuGpsEstacionamentoView = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenu();
        menuPagamentoView = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        subMenuTelaPrincipal = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        subMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Sejam Bem Vindos!");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        painelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelInterno.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/Vaga02.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelInterno.add(jButton1);
        jButton1.setBounds(0, 150, 120, 90);

        btnCadastroEstacionamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/Est11.jpg"))); // NOI18N
        btnCadastroEstacionamento.setToolTipText("Estacionamento");
        btnCadastroEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroEstacionamentoActionPerformed(evt);
            }
        });
        painelInterno.add(btnCadastroEstacionamento);
        btnCadastroEstacionamento.setBounds(0, 40, 120, 90);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Cadastros:");
        painelInterno.add(jLabel2);
        jLabel2.setBounds(0, 0, 110, 30);

        btnCadastroMotoristas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/motorista.jpg"))); // NOI18N
        btnCadastroMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroMotoristasActionPerformed(evt);
            }
        });
        painelInterno.add(btnCadastroMotoristas);
        btnCadastroMotoristas.setBounds(0, 260, 120, 90);

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/admin04.jpg"))); // NOI18N
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        painelInterno.add(btnAdmin);
        btnAdmin.setBounds(500, 80, 150, 80);

        btnGps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/Localiz04.jpg"))); // NOI18N
        btnGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGpsActionPerformed(evt);
            }
        });
        painelInterno.add(btnGps);
        btnGps.setBounds(540, 270, 110, 80);

        btnRegistroVagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/registro01.jpg"))); // NOI18N
        btnRegistroVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroVagasActionPerformed(evt);
            }
        });
        painelInterno.add(btnRegistroVagas);
        btnRegistroVagas.setBounds(240, 260, 150, 90);

        btnPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/pagamento04.jpg"))); // NOI18N
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });
        painelInterno.add(btnPagamento);
        btnPagamento.setBounds(500, 180, 150, 80);

        bntFecharTelaBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/exit.jpg"))); // NOI18N
        bntFecharTelaBemVindo.setToolTipText("Fechar Tela Bem Vindo");
        bntFecharTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFecharTelaBemVindoActionPerformed(evt);
            }
        });
        painelInterno.add(bntFecharTelaBemVindo);
        bntFecharTelaBemVindo.setBounds(500, 0, 150, 70);

        labelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/Logomarca.jpeg"))); // NOI18N
        painelInterno.add(labelPainelFundo);
        labelPainelFundo.setBounds(-10, -50, 670, 430);

        jInternalFrameBemVindo.getContentPane().add(painelInterno);
        painelInterno.setBounds(0, 30, 660, 350);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento do Open And Park!");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 0, 680, 430);

        menuAdmin.setText("Admin");

        menuUsuarioAdminView.setText("Login");
        menuUsuarioAdminView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioAdminViewActionPerformed(evt);
            }
        });
        menuAdmin.add(menuUsuarioAdminView);

        barraMenu.add(menuAdmin);

        menuCadastroVagas.setText("Cadastro");

        menuCadastroEstacionamento.setText("Estacionamento");
        menuCadastroEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroEstacionamentoActionPerformed(evt);
            }
        });
        menuCadastroVagas.add(menuCadastroEstacionamento);

        menuCadastroVaga.setText(" Vaga");
        menuCadastroVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroVagaActionPerformed(evt);
            }
        });
        menuCadastroVagas.add(menuCadastroVaga);

        menuCadastroMotorista.setText("Motoristas");
        menuCadastroMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroMotoristaActionPerformed(evt);
            }
        });
        menuCadastroVagas.add(menuCadastroMotorista);

        barraMenu.add(menuCadastroVagas);

        menuRegistro.setText("Registro ");

        menuGuardarRegistroVaga.setText("Vaga");
        menuGuardarRegistroVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarRegistroVagaActionPerformed(evt);
            }
        });
        menuRegistro.add(menuGuardarRegistroVaga);

        barraMenu.add(menuRegistro);

        menuGps.setText("Gps");

        menuGpsEstacionamentoView.setText("Localização de Estacionamento");
        menuGpsEstacionamentoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGpsEstacionamentoViewActionPerformed(evt);
            }
        });
        menuGps.add(menuGpsEstacionamentoView);

        barraMenu.add(menuGps);

        menuPagamento.setText("Pagamento");

        menuPagamentoView.setText("Cartão de crédito");
        menuPagamentoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagamentoViewActionPerformed(evt);
            }
        });
        menuPagamento.add(menuPagamentoView);

        barraMenu.add(menuPagamento);

        menuFerramentas.setText("Ferramentas");

        subMenuTelaPrincipal.setText("Tela Principal");
        subMenuTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTelaPrincipalActionPerformed(evt);
            }
        });
        menuFerramentas.add(subMenuTelaPrincipal);

        barraMenu.add(menuFerramentas);

        menuSair.setText("Sair");

        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuSair.add(subMenuSair);

        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        setSize(new java.awt.Dimension(679, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroEstacionamentoActionPerformed
        EstacionamentoView tela =  new EstacionamentoView();
        tela.setVisible(true);
     
    }//GEN-LAST:event_menuCadastroEstacionamentoActionPerformed

    private void menuCadastroMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroMotoristaActionPerformed
        UsuarioMotoristaView tela = new UsuarioMotoristaView();
        tela.setVisible(true);
    }//GEN-LAST:event_menuCadastroMotoristaActionPerformed

    private void menuCadastroVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroVagaActionPerformed
        VagaView tela = new VagaView();
        tela.setVisible(true);
                
    }//GEN-LAST:event_menuCadastroVagaActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        UsuarioAdminView tela = null;  //**Acrescentei o try catch aqui para o ModuloConexao2 e null tambem
        try {
            tela = new UsuarioAdminView();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void bntFecharTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFecharTelaBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();//Fecha a tela do Bem Vindo(InternalFrame)
    }//GEN-LAST:event_bntFecharTelaBemVindoActionPerformed

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        //try {   //**
         //   conecta.desconecta();
       // } catch (SQLException ex) {
         //   Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
       // }
        System.exit(0);//Fecha o sistema por completo  
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void subMenuTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTelaPrincipalActionPerformed
        TelaPrincipalView tela= null;  //**Acrescentei o try catch aqui para o ModuloConexao2 e o null
        try {
            tela = new TelaPrincipalView();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();//Fecha a tela anterior(Que é a propria tela principal)
        
    }//GEN-LAST:event_subMenuTelaPrincipalActionPerformed

    private void btnCadastroEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroEstacionamentoActionPerformed
         EstacionamentoView tela =  new EstacionamentoView();
         tela.setVisible(true);
    }//GEN-LAST:event_btnCadastroEstacionamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VagaView tela = new VagaView();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadastroMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroMotoristasActionPerformed
         UsuarioMotoristaView tela = new UsuarioMotoristaView();
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastroMotoristasActionPerformed

    private void menuGuardarRegistroVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarRegistroVagaActionPerformed
        GuardarRegistroVagaView tela = new GuardarRegistroVagaView();
        tela.setVisible(true);
    }//GEN-LAST:event_menuGuardarRegistroVagaActionPerformed

    private void btnRegistroVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVagasActionPerformed
        GuardarRegistroVagaView tela = new GuardarRegistroVagaView();
        tela.setVisible(true);
    }//GEN-LAST:event_btnRegistroVagasActionPerformed

    private void menuPagamentoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagamentoViewActionPerformed
        PagamentoView tela = new PagamentoView();
        tela.setVisible(true);
    }//GEN-LAST:event_menuPagamentoViewActionPerformed

    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        PagamentoView tela = new PagamentoView();
        tela.setVisible(true);
    }//GEN-LAST:event_btnPagamentoActionPerformed

    private void menuGpsEstacionamentoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGpsEstacionamentoViewActionPerformed
        GpsEstacionamentoView tela = new GpsEstacionamentoView();
        tela.setVisible(true);
    }//GEN-LAST:event_menuGpsEstacionamentoViewActionPerformed

    private void menuUsuarioAdminViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioAdminViewActionPerformed
        UsuarioAdminView tela = null;  //**Acrescentei o try catch aqui para o ModuloConexao2
        try {
            tela = new UsuarioAdminView();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
    }//GEN-LAST:event_menuUsuarioAdminViewActionPerformed

    private void btnGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGpsActionPerformed
        GpsEstacionamentoView tela = new GpsEstacionamentoView();
        tela.setVisible(true);
    }//GEN-LAST:event_btnGpsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  //**Acrescentei o try catch aqui para o ModuloConexao2
                try {
                    new TelaPrincipalView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton bntFecharTelaBemVindo;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCadastroEstacionamento;
    private javax.swing.JButton btnCadastroMotoristas;
    private javax.swing.JButton btnGps;
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnRegistroVagas;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPainelFundo;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuCadastroEstacionamento;
    private javax.swing.JMenuItem menuCadastroMotorista;
    private javax.swing.JMenuItem menuCadastroVaga;
    private javax.swing.JMenu menuCadastroVagas;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuGps;
    private javax.swing.JMenuItem menuGpsEstacionamentoView;
    private javax.swing.JMenuItem menuGuardarRegistroVaga;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenuItem menuPagamentoView;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuUsuarioAdminView;
    private javax.swing.JPanel painelInterno;
    private javax.swing.JMenuItem subMenuSair;
    private javax.swing.JMenuItem subMenuTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
