/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fja.view;
import br.edu.fja.model.DaoUtil;
import java.sql.* ;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeRegExp.ignoreCase;


public class UsuarioAdminView extends javax.swing.JFrame {
   // ModuloConexao conecta = new   ModuloConexao();
    //É mais um conjunto de Fremework (3), conjunto de biblioteca para exucutar o mysql1
    //***Connection conexao = null; Desativei da classe ModuloConexao
//Criando duas variaveis especiais de apoio a coxecao com o BD, isso para cada Form!!
   
    Connection conexao = null;
    PreparedStatement  ps = null;
    ResultSet rs = null;  
    
    public void logar() throws SQLException{
        String sql = "select * from usuario_admin where usuario=? and senha =?";
        try {
            //As linhas abaixo preparam a consulta ao banco em funcao do que foi digitado
            //nas caixas de texto. o ? é susbstituido pelo conteudo das variaveis
            ps = conexao.prepareStatement(sql);
            ps.setString(1, txtUsuario.getText());
            ps.setString(2, txtSenha.getText());
        
          //A linho abaiso executa a Query
          rs = ps.executeQuery();
          //Se existir usuário e senha correspondente
          if(rs.next()){
               
              
               TelaPrincipalView tela = new TelaPrincipalView();
               tela.setVisible(true);
               dispose();//Comando para puxar a tela anterior
              
              
          }else{
             
              JOptionPane.showMessageDialog(null, "Usuario ou senha invalidos");
              System.exit(0);
          
          }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
       
      
    public UsuarioAdminView() throws SQLException {
        initComponents();
        
         conexao = DaoUtil.conector();
    
       // Esta linha serve de apoio ao status da conexao!
         System.out.println("Conexão" + conexao);
    
        
        if(conexao != null){
      
            labelStatus.setText("Conectado ao Banco");
            //labelStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fja/img/conectado.jpg")));
        }else{
            labelStatus.setText("Não Conectado ao Banco");
            //labelStatus.setIcon(new javax.swing.ImageIcon(getClass ().getResource("/br/com/fja/img/desconectado.png")));
        }
                
        
        
        //setLocationRelativeTo(null);Centralizar a tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnSair = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        labelFundoTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuário Administrador");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font(".SF NS Text", 1, 24)); // NOI18N
        getContentPane().setLayout(null);

        labelUsuario.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        labelUsuario.setText("  Usuário:");
        labelUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(labelUsuario);
        labelUsuario.setBounds(40, 70, 100, 40);

        labelSenha.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        labelSenha.setText("   Senha:");
        labelSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(labelSenha);
        labelSenha.setBounds(40, 130, 100, 40);

        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(150, 70, 267, 40);

        txtSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtSenha);
        txtSenha.setBounds(150, 130, 194, 40);

        btnSair.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(102, 255, 255)));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(230, 210, 120, 50);

        btnLogin.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 0, 204), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(100, 210, 120, 50);

        labelStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelStatus.setText("Status");
        getContentPane().add(labelStatus);
        labelStatus.setBounds(200, 320, 170, 30);

        labelFundoTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fja/img/Logomarca.jpeg"))); // NOI18N
        labelFundoTelaLogin.setToolTipText("");
        labelFundoTelaLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labelFundoTelaLogin);
        labelFundoTelaLogin.setBounds(10, 10, 500, 380);

        setSize(new java.awt.Dimension(517, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        try {
            logar();
            TelaPrincipalView tela = new TelaPrincipalView();
            tela.setVisible(true);
            dispose();//Comando para puxar a tela anterior
            
            /*
            try {
            if(txtUsuario.getText().equalsIgnoreCase("Admin")&&txtSenha.getText().equals("12345")){
            
            TelaPrincipalView tela = new TelaPrincipalView();
            tela.setVisible(true);
            dispose();//Comando para puxar a tela anterior
            
            
            
            }else{
            JOptionPane.showMessageDialog(null, "Usuario e senha Incorretos");
            
            
            
            }
            } catch (SQLException ex) {
            Logger.getLogger(UsuarioAdminView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            */
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioAdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnLoginActionPerformed
    
      
      
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mc OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  //**Acrescentei o try catch aqui para o ModuloConexao2
                try {
                    new UsuarioAdminView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UsuarioAdminView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel labelFundoTelaLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
